INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi University (HANU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vietnam National University, (Hanoi – VNU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vietnam National University, (Ho Chi Minh City – VNU-HCM)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Transport and Communications (UTC)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'National Economics University (NEU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi University of Mining and Geology (HUMG)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'The University of Industrial Fine Arts (MTCN)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Foreign Trade University (FTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi University of Physical Education and Sports (HUPES)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Thuongmai University (TMU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi University of Civil Engineering (HUCE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Economics Ho Chi Minh City (UEH)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City University of Law (ULaw)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City Open University (HCMOU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Nong Lam University Ho Chi Minh City Viet Nam (NLU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City University of Technology and Education (HCMUTE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City University of Education (HCMUE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City University of Physical Educations and Sport (HCMUPES)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Can Tho University (CTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Dalat University (DLU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Dong Thap University (DThU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Kien Giang University (KGU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Nha Trang University (NTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Quy Nhon University (QNU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hung Yen University of Technology and Education (HYUTE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Tay Bac University (TBU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Tay Nguyen University (TNU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vietnamese-German University (VGU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vinh University (VinhUni)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi Medical University (HMU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi University of Public Health (HUPH)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'VietNam University Of Traditional Medicine (VUTM)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City Medicine and Pharmacy University (YDS)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Pham Ngoc Thach University of Medicine (TYS)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Haiphong University Of Medicine and Pharmacy (HPMU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'ThaiBinh University of Medicine and Pharmacy (TBUMP)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Nam Dinh University of Nursing (NDUN)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hai Duong Medical technical University (HMTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Da Nang University of Medical Technology and Pharmacy (DUMTP)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Viet Nam National Academy of Music (VNAM)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Viet Nam Academy of Dance (VNAD)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi University of Culture (HUC)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vietnam University of Fine Arts (VNUFA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi Academy of Theater and Cinema (SKDA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'The Conservatory of Ho Chi Minh City (HCMCONS)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City College of Stage Performance and Cinematics (SKDAHCM)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City University of Fine Arts (HCMUFA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh University Of Sport (USH)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City University of Culture (VHS)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hue Academy of Music (HVA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Bac Ninh Sport University (UPES1)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Da Nang University of Physical Education and Sport (DSU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi University of Industry (HaUI)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Viet - Hung Industrial University (VIU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Electric Power University (EPU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Industrial University of Ho Chi Minh City (IUH)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City University of Food Industry (HUFI)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Quang Ninh University of Industry (QNUI)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Viet Tri University Of Industry (VUI)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Economics - Technology for Industries (UNETI)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University Of Transport Technology (UTT)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Transport Ho Chi Minh City (UTH)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vietnam Maritime University (VMU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi Architectural University (HAU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Architecture Ho Chi Minh City (UAH)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Mien Trung University of Civil Engineering (MUCE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'MienTay Construction University (MTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Labour and Social Affairs (ULSA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Nam Dinh University of Technology Education (NUTE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vinh University of Technology Education (VinhUTE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vinh Long University of Technology and Education (VLUTE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'ThuyLoi University (TLU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Bac Giang Agriculture And Forestry University (BAFU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Academy of Finance (AOF)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Finance - Marketing (UFM)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Finance and Accountancy (UFA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'The University Of Finance And Business Administration (UFBA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh National Academy of Politics (HCMA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Academy of Journalism and Communication (AJC)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi University of Natural Resources and Environment (HUNRE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh University of Natural Resources and Environment (HCMUNRE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Academy Of Policy and Development (APD)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vietnam Institute of Science Technology and Innovation (VISTI)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Diplomatic Academy of Vietnam (DAV)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'National Academy of Public Administration (NAPA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Posts and Telecommunications Institute of Technology (PTIT)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi Law University (HLU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Banking Academy of Vietnam (AOB)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'PetroVietnam University (PVU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vietnam Court Academy (VCA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vietnam Trade Union University (TUU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ton Duc Thang University (TDTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vietnam Women`s Academy (VWA)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vietnam Academy for Ethnic Minorities (VAEM)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Graduate University of Sciences and Technology (GUST)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Science and Technology of Hanoi (USTH)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Graduate Academy of Social Sciences (GASS)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi Procuratorate University (HPU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi Metropolitan University (HNMU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh Cadre Academy (HVC)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Saigon University (SGU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Haiphong University (DHHP)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Can Tho University of Technology (CTUT)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Bac Lieu University (BLU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Thu Dau Mot University (TDMU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Dong Nai Technology University (DNU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ha Tinh University (HTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Hai Duong (UHD)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Nghe An College of Economics (NAUE)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Vinh Medical University (VMU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hoa Lu University (HLUV)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hung Vuong University (HVU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Phu Yen University (PYU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Quang Binh University (QBU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Quang Nam University (QNamUni)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Pham Van Dong University (PDU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ha Long University (UHL)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Thai Binh University (TBU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hong Duc University (HDU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Culture, Sports and Tourism in Thanh Hóa (DVTDT)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Tien Giang University (TGU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Tra Vinh University (TVU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Tan Trao University (TTrU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'CMC University (CMC)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Technology and Management (UTM)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Dai Nam University (DNU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Dong Do University (HDIU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'FPT University (FPTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hoa Binh University (HBU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi University of Business and Technology (HUBT)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Nguyen Trai University (NTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Phenikaa University');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hanoi Financial and Banking University (FBU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Thanh Do University (TDU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Thang Long University (TLU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'VinUniversity (VinUni)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City University of Technology (HUTECH)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City University of Economics and Finance (UEF)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Gia Dinh University (GDU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hoa Sen University (HSU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hung Vuong University Ho Chi Minh City (HVUH)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ho Chi Minh City University of Foreign Languages – Information Technology (HUFLIT)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Nguyen Tat Thanh University (NTTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Hong Bang University (HBU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Saigon International University (SIU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Van Hien University (VHU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Baria-Vungtau University (BVU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Dong A University (EAUT)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Kinh Bac (UKB)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Bac Ha International University (BHIU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Binh Duong University (BDU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Binh Duong Economics and Technology University (BETU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Eastern International University (EIU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Quang Trung University (QTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'University of Phan Thiet (UPT)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Nam Can Tho University (NCTU)');
INSERT INTO university (deleted, name) VALUES (FALSE, 'Ha Noi University of Science and Technology (HUST)');